# Generated by Django 3.2.4 on 2021-07-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210727_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='affiliate_url',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(default='Один из курсов по математике'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='default.png', upload_to='courses_images'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(default='ЕГЭ', max_length=25),
        ),
    ]
