# Generated by Django 3.2.4 on 2021-07-27 16:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210727_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_published', models.DateTimeField(verbose_name='Дата публикации')),
                ('article_image', models.ImageField(upload_to='news_images/')),
                ('article_content', tinymce.models.HTMLField()),
                ('article_slug', models.SlugField()),
            ],
        ),
    ]
